### ISSUE TITLE
Provide a testcontainer based on Keycloak.X

### ISSUE THREAD

**Issue by dasniko** [dasniko/testcontainers-keycloak#10]
Keycloak.X see https://www.keycloak.org/2020/12/first-keycloak-x-release.adoc.html

- [x]  Standard methods to spin up a testcontainer
- [x] Importing a realm from a file
- [x] HTTPS/TLS support
- [x] Extension support

**Comment by OLibutzki** [comment]
Any progress on this one? We decided to reduce the usage of Keycloak in our integration tests, because it takes about 40 or 50 seconds to start. With Keycloak.X this might change drastically as its Docker container starts in about 8 seconds on my machine.

**Comment by dasniko** [comment]
Unfortunately no, not even started yet.

At least, I created a [`v2` branch](https://github.com/dasniko/testcontainers-keycloak/tree/v2). PRs are welcome. 🙂

**Comment by dasniko** [comment]
So, here it begins...

I've created also a [`keycloak-x`](https://github.com/dasniko/testcontainers-keycloak/tree/keycloak-x) branch, starting to implement all the things...

Well, it seems, it's a bit more complicated than expected.
For proper performance, it is recommended to build a custom image, based on the official keycloak-x one and doing all needed and time consuming configuration at build time.
There's the `--auto-config` option, which I'm currently using to configure things at container startup, but this is slowing down container startup. Starting a container in this way, it takes, depending on the environment, between 20 and 30 seconds. Nothing won.

Any ideas and contributions are welcome!

**Comment by dasniko** [comment]
I pushed the `keycloak-x` branch rebased on current changes and now also with a first approach for custom extension deployment. (also Java 11 is the minimum and JUnit 5 is now used)

Feedback is welcome!

**Comment by dasniko** [comment]
Thinking about removing `. withRealmImportFile/s()` as Keycloak-X doesn't support auto-importing realms on container startup. This currently needs a custom image, which I build on runtime when needed and call `kc.sh import...`.
Users can (should) handle this in test initializer method (`@BeforeAll` or similar) via the Keycloak admin client.
WDYT?

**Comment by OLibutzki** [comment]
We always preconfigure the testrealm by importing it. Our current workflow is like creating a realm using the Admin UI, exporting it and importing it in the tests.

It would be possible to use the admin client to initialize the realm, too, but it's not as convenient as importing a pre-configured realm.

**Comment by sventorben** [comment]
> We always preconfigure the testrealm by importing it. Our current workflow is like creating a realm using the Admin UI, exporting it and importing it in the tests.

I do the same most of the time.

> It would be possible to use the admin client to initialize the realm, too, but it's not as convenient as importing a pre-configured realm.

You could use the admin api for the initial import. It's a no brainer, see here: https://github.com/sventorben/keycloak-restrict-client-auth/pull/20/files#diff-257b31b092c617ce8d8176ba78874942e89c69360aef023f9c56a62b4b49fbcbR77
The `test-realm.json` is a simple export. With this approach I am still able to configure the realm via the admin UI and export it.

**Comment by dasniko** [comment]
Yes, I was thinking about the way @sventorben mentioned.
I don't know if I can get it in the TC lifecycle, but I'll give it a try. Would be a better way than the current approach with a custom image built at runtime.

**Comment by dasniko** [comment]
Thanks guys, this was a good one.

I think, we have now a pretty good first version. If you like, go ahead and test it, e.g. via Jitpack:
https://jitpack.io/#dasniko/testcontainers-keycloak/keycloak-x-SNAPSHOT

**Comment by OLibutzki** [comment]
I just tried your branch and I get an error when trying to import the realm:
```
09:43:41.158 [main] ERROR 🐳 [quay.io/keycloak/keycloak-x:15.0.2] - Could not start container
java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4737) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3398) ~[jackson-databind-2.11.4.jar:2.11.4]
	at dasniko.testcontainers.keycloak.KeycloakContainer.containerIsStarted(KeycloakContainer.java:124) ~[testcontainers-keycloak-keycloak-x-1.8.1-g6ea1e43-17.jar:?]
	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:688) ~[testcontainers-1.16.2.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:504) ~[testcontainers-1.16.2.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331) ~[testcontainers-1.16.2.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329) ~[testcontainers-1.16.2.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317) ~[testcontainers-1.16.2.jar:?]
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:242) ~[junit-jupiter-1.16.0.jar:?]
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:229) ~[junit-jupiter-1.16.0.jar:?]
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$1(TestcontainersExtension.java:59) ~[junit-jupiter-1.16.0.jar:?]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$4(ExtensionValuesStore.java:86) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.computeValue(ExtensionValuesStore.java:223) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:211) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.evaluate(ExtensionValuesStore.java:191) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.access$100(ExtensionValuesStore.java:171) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:89) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:53) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$beforeAll$2(TestcontainersExtension.java:59) ~[junit-jupiter-1.16.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:59) ~[junit-jupiter-1.16.0.jar:?]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78) ~[junit-jupiter-engine-5.7.1.jar:5.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108) ~[junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) ~[junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) ~[junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) [junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) [junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96) [junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84) [junit-platform-launcher-1.7.1.jar:1.7.1]
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
09:43:41.219 [main] ERROR 🐳 [quay.io/keycloak/keycloak-x:15.0.2] - Log output from the failed container:
LogManager error of type WRITE_FAILURE: The delayed handler's queue was overrun and log record(s) were lost. Did you forget to configure logging?
2021-11-02 08:43:26,597 INFO  [org.key.url.DefaultHostnameProviderFactory] (main) Frontend: <request>, Admin: <frontend>, Backend: <request>
2021-11-02 08:43:28,671 INFO  [org.key.con.liq.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2021-11-02 08:43:31,705 INFO  [org.key.pro.qua.QuarkusCacheManagerProvider] (main) Loading cluster configuration from /opt/jboss/keycloak/bin/../conf/cluster-local.xml
2021-11-02 08:43:32,021 WARN  [org.inf.PERSISTENCE] (main) ISPN000554: jboss-marshalling is deprecated and planned for removal
2021-11-02 08:43:32,023 INFO  [org.inf.CONTAINER] (main) ISPN000128: Infinispan version: Infinispan 'Corona Extra' 11.0.9.Final
2021-11-02 08:43:32,142 INFO  [org.inf.PERSISTENCE] (main) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2021-11-02 08:43:32,452 INFO  [org.key.con.inf.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_927570, Site name: null
2021-11-02 08:43:32,578 INFO  [org.key.services] (main) KC-SERVICES0050: Initializing master realm
2021-11-02 08:43:36,149 INFO  [org.key.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
2021-11-02 08:43:36,335 INFO  [io.quarkus] (main) Keycloak 15.0.2 on JVM (powered by Quarkus 1.13.3.Final) started in 13.656s. Listening on: http://0.0.0.0:8080
2021-11-02 08:43:36,336 INFO  [io.quarkus] (main) Profile dev activated. 
2021-11-02 08:43:36,336 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mysql, jdbc-postgresql, keycloak, mutiny, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vertx, vertx-web]
```

Here is the testrealm-config I used: [test-realm.zip](https://github.com/dasniko/testcontainers-keycloak/files/7459144/test-realm.zip)

**Comment by dasniko** [comment]
Thanks for reporting. I'll investigate later this week.
(this might be a classloader issue)

**Comment by dasniko** [comment]
Please try again, there should be a new snapshot available through JitPack.

Please note, that if you used `.withRealmImportFile("test-realm.json")` so far, you'll now have to prefix it with `/`: `.withRealmImportFile("/test-realm.json")`, so that it's relative to your classpath root.

**Comment by OLibutzki** [comment]
With the latest snapshot I have been able to run our tests against the Keycloak.X image without the need to perform any further adjustments! That's great.

**Comment by sventorben** [comment]
I can confirm this. Works like a charm.

https://github.com/sventorben/keycloak-restrict-client-auth/runs/4098833912?check_suite_focus=true

**Comment by dasniko** [comment]
Ok then, we'll "just" have to wait for the RH team to publish the next preview and finally the first release.

**Comment by sventorben** [comment]
I was just trying to test my custom keycloak extensions with the latest Keyclok.X image, version `15.1.0`.
It looks like there are some incompatible changes.

`--auto-config` is now `--auto-build` and I could not get the container to start with this and any additional options. What worked though was to call `start-dev` command instead.

Also the location for custom extensions / providers has been changed to `/opt/keycloak/providers`.

[Here](https://github.com/sventorben/keycloak-restrict-client-auth/pull/29/commits/e73b82eca1fe852e65fc292c97e2dce25e04208d) is what I had to change for this to work for me.

**Comment by dasniko** [comment]
Thanks @sventorben for the input. I already started yesterday with first adjustments. I hope to come up with a new snapshot beginning next week.

**Comment by dasniko** [comment]
Using `start-dev` sets implicitly `--profile=dev` and `--auto-build`, no matter if it's needed or not. This adds overhead to the container startup.
Just using `start` with `--profile=dev` prepended, doesn't work. The dev profile seems only to work with `start-dev`.

I'm now setting a fake profile to not using implicitly `prod` and setting other properties just as needed. If there are settings/properties which require build-time configuration, I add the `--auto-build` option on the fly (and print a warning to the logs, that this adds overhead). With this, you get in simple cases, when you don't need build-time configs, a faster container startup.

**Comment by sventorben** [comment]
Works for me. Thanks @dasniko!

**Comment by OLibutzki** [comment]
Hi @dasniko,

with the Release of Keycloak 17 the Quarkus distribution is the new default. Are there any plans for a testcontainers-keycloak release that supports the Quarkus based Keycloak in the near future?

**Comment by dasniko** [comment]
Of course, otherwise this discussion and the related keycloak-x branch wouldn't exist. See also the note on the readme page. 

I'm currently very busy and this is project is maintained in my spare time and offered without charge. So, I will update all the things, move to the most recent version, adjust to changes and all. As soon as I find time.

**Comment by sventorben** [comment]
For reference: There is a change in the naming pattern for the containres from version 17.0.0
https://groups.google.com/g/keycloak-dev/c/RQpL7L4FRy0

**Comment by dasniko** [comment]
Release 2.0.0 published: https://github.com/dasniko/testcontainers-keycloak/releases/tag/2.0.0
Maven Central release done, takes some time to update Maven Central index.

Closing this issue as migration is done.
Thanks for your support.
If there are problems with new release, please open news issues here on GitHub.
