### ISSUE TITLE
Failed to read realm JSON file with the new version 2.1.1 (and thus KC 17)

### ISSUE THREAD

**Issue by semangard** [dasniko/testcontainers-keycloak#65]
Hello,

I was using KC test container for a while.
It was working correctly with the version 1.9.0.
Then I deciced today to test it with version 2.1.1 (and thus KC 17)
![image](https://user-images.githubusercontent.com/57065741/158069299-00a81843-6280-410c-8343-31b1734dcb55.png)
but KC does not want to start anymore, I have the exception : 

`22-03-13 17:26:58.031 /  INFO   --- [eam--1508215392] 🐳 [quay.io/keycloak/keycloak:17.0.0]    : STDOUT: 2022-03-13 16:21:53,586 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, infinispan-client, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-03-13 17:26:58.041 /  INFO   --- [           main] o.t.c.wait.strategy.HttpWaitStrategy     : /gracious_lederberg: Waiting for 120 seconds for URL: http://localhost:56189/ (where port 56189 maps to container port 8080)
2022-03-13 17:26:58.082 /  INFO   --- [           main] 🐳 [quay.io/keycloak/keycloak:17.0.0]    : Container quay.io/keycloak/keycloak:17.0.0 started in PT1.3515094S
2022-03-13 17:26:58.082 /  INFO   --- [           main] 🐳 [quay.io/keycloak/keycloak:17.0.0]    : Connect to Keycloak container to import given realm files.
2022-03-13 17:26:58.685 /  INFO   --- [           main] 🐳 [quay.io/keycloak/keycloak:17.0.0]    : Importing realm from file keycloak-test-realm.json
2022-03-13 17:26:58.821 / ERROR   --- [           main] 🐳 [quay.io/keycloak/keycloak:17.0.0]    : Could not start container

java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4757)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3478)
	at dasniko.testcontainers.keycloak.KeycloakContainer.containerIsStarted(KeycloakContainer.java:185)
	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:688)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:504)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at ch.hcuge.keycloak.test.extension.KeyCloakTestContainerExtension.beforeAll(KeyCloakTestContainerExtension.java:63)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
`

It seems it failed while importing my realm JSON (cf. attached file)
[keycloak-test-realm.json.txt](https://github.com/dasniko/testcontainers-keycloak/files/8240149/keycloak-test-realm.json.txt)

Test extension :
![image](https://user-images.githubusercontent.com/57065741/158069500-456ea693-3fc7-4722-94a4-4eda78a07160.png)

**Comment by semangard** [comment]
FYI : it was still working also with:
KC test container 1.10.0
+ KC 17.0.0-legacy"

**Comment by dasniko** [comment]
This is most probably because you specified the path of the realm file not properly.
Where is your json file located? If it's, e.g. `src/test/resources/keycloak-test-realm.json`, you have to set `.withRealmImportFile"/keycloak-test-realm.json")`, not `...("keycloak-test-realm.json")`.

**Comment by semangard** [comment]
It was working properly with previous version... and I changed only version'numbers

test file is here:
![image](https://user-images.githubusercontent.com/57065741/158076197-3e2d6e10-8e93-48f1-b04b-a15a9b610dda.png)

**Comment by dasniko** [comment]
The major version changed, so it's possible that parts of your previous environment doesn't work anymore with the most recent version. Also, it's very likely, that the legacy behavior only worked by accident.
Set the `/` in front of your realm file and you should be good to go.

**Comment by semangard** [comment]
Seems better witth the /

![image](https://user-images.githubusercontent.com/57065741/158077441-85e2d666-b1d6-4e54-856a-c2411a07a4ee.png)

But now I am facing another exception:

`
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalStateException: The Issuer "http://localhost:60190/realms/test" provided in the configuration metadata did not match the requested issuer "http://localhost:60190//realms/test"
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 174 more
Caused by: java.lang.IllegalStateException: The Issuer "http://localhost:60190/realms/test" provided in the configuration metadata did not match the requested issuer "http://localhost:60190//realms/test"
`
with unchanged test config:
![image](https://user-images.githubusercontent.com/57065741/158077524-31e7cacc-11d4-4048-b74c-95489fceb495.png)

and: 
![image](https://user-images.githubusercontent.com/57065741/158077557-1c2cf5cc-e95b-4978-8735-312f251a1214.png)

**Comment by semangard** [comment]
OK it works after manually removing the trailing slash:
![image](https://user-images.githubusercontent.com/57065741/158078088-7d7ff8fe-6d81-476b-938d-e931cb7cecd9.png)

BUT I have now a 3thd issue: if the test container is not removed after a test (which was working properly with previous versions) then I have the following exception while executing next test:

![image](https://user-images.githubusercontent.com/57065741/158078134-0c609c09-d203-436d-9e82-e0ac59b10741.png)

I looks like it tries to reimport the realm which fails because it was already imported into the kept up and running KC test container

**Comment by dasniko** [comment]
Please:

- Don't paste images for code-fragments and log outputs. There are good posibilities here to format the data properly, so that it is easy readable. Images are not and additionally half of probably valuable information is cut.
- Open a new issue for your current error. As the initial issue is solved, I'll close this ticket now.

Thanks.
